import { ClassicListenersCollector } from "@empirica/core/admin/classic";
export const Empirica = new ClassicListenersCollector();


var TIC_TAC_TOE = {
  index: 1,
  "board-x": 3,
  "board-y": 3,
  N: 3,
  "N-for-win": 1,
  "player1-diag-win": 1,
  "player1-hv-win": 1,
  "player2-diag-win": 1,
  "player2-hv-win": 1,
  "diff-win": 0,
  "player1-2pieces": 0,
  "player2-2pieces": 0,
  label: "simple-win",
  orig_stimuli_id: "3.0*3.0*3 pieces in a row wins.",
  stimuli_id: "3.0*3.0*3 pieces in a row wins. Horizontal, vertical, and diagonal all count.",
};

var STIMULI_BATCHES = [[{'index': 10,
  'board-x': 10,
  'board-y': 10,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'simple-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '10.0*10.0*4 pieces in a row wins.',
  'stimuli_id': '10.0*10.0*4 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 111,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 0,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'player1-constraintA',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*Each player needs 4 pieces in a row to win. The first player cannot win by making a diagonal row (only horizontal and vertical rows count), but the second player does not have this restriction.',
  'stimuli_id': '7.0*7.0*Each player needs 4 pieces in a row to win. The first player cannot win by making a diagonal row (only horizontal and vertical rows count), but the second player does not have this restriction.'},
 {'index': 33,
  'board-x': 4,
  'board-y': 6,
  'N': 5,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '4.0*6.0*5 pieces in a row wins.',
  'stimuli_id': '4.0*6.0*5 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 53,
  'board-x': 4,
  'board-y': 4,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 0,
  'player1-hv-win': 1,
  'player2-diag-win': 0,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'no-diag',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '4.0*4.0*3 pieces in a row wins. However, a player cannot win by making a diagonal row. Only horizontal and vertical rows count.',
  'stimuli_id': '4.0*4.0*3 pieces in a row wins. However, a player cannot win by making a diagonal row. Only horizontal and vertical rows count.'},
 {'index': 42,
  'board-x': 3,
  'board-y': 3,
  'N': 3,
  'N-for-win': 0,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'loss',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '3.0*3.0*3 pieces in a row loses.',
  'stimuli_id': '3.0*3.0*3 pieces in a row loses. Horizontal, vertical, and diagonal all count.'}],
[{'index': 117,
  'board-x': 10,
  'board-y': 10,
  'N': 5,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 0,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'player1-constraintB',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '10.0*10.0*Each player needs 5 pieces in a row to win. The first player can only win by making a diagonal row, but the second player does not have this restriction.',
  'stimuli_id': '10.0*10.0*Each player needs 5 pieces in a row to win. The first player can only win by making a diagonal row, but the second player does not have this restriction.'},
 {'index': 30,
  'board-x': 4,
  'board-y': 6,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '4.0*6.0*4 pieces in a row wins.',
  'stimuli_id': '4.0*6.0*4 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 91,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 1,
  'label': 'player2-2pieces',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*4 pieces in a row wins. The second player can place 2 pieces as their first move, while the first player can only place 1 piece as their first move.',
  'stimuli_id': '7.0*7.0*4 pieces in a row wins. The second player can place 2 pieces as their first move, while the first player can only place 1 piece as their first move. Horizontal, vertical, and diagonal all count.'},
 {'index': 61,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 0,
  'player1-hv-win': 1,
  'player2-diag-win': 0,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'no-diag',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*4 pieces in a row wins. However, a player cannot win by making a diagonal row. Only horizontal and vertical rows count.',
  'stimuli_id': '7.0*7.0*4 pieces in a row wins. However, a player cannot win by making a diagonal row. Only horizontal and vertical rows count.'},
 {'index': 25,
  'board-x': 2,
  'board-y': 5,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '2.0*5.0*3 pieces in a row wins.',
  'stimuli_id': '2.0*5.0*3 pieces in a row wins. Horizontal, vertical, and diagonal all count.'}],
[{'index': 107,
  'board-x': 10,
  'board-y': 10,
  'N': 5,
  'N-for-win': 1,
  'player1-diag-win': 0,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'player1-constraintA',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '10.0*10.0*Each player needs 5 pieces in a row to win. The first player cannot win by making a diagonal row (only horizontal and vertical rows count), but the second player does not have this restriction.',
  'stimuli_id': '10.0*10.0*Each player needs 5 pieces in a row to win. The first player cannot win by making a diagonal row (only horizontal and vertical rows count), but the second player does not have this restriction.'},
 {'index': 31,
  'board-x': 4,
  'board-y': 9,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '4.0*9.0*4 pieces in a row wins.',
  'stimuli_id': '4.0*9.0*4 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 17,
  'board-x': 5,
  'board-y': 5,
  'N': 2,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'simple-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*2 pieces in a row wins.',
  'stimuli_id': '5.0*5.0*2 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 82,
  'board-x': 3,
  'board-y': 3,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 1,
  'label': 'player2-2pieces',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '3.0*3.0*3 pieces in a row wins. The second player can place 2 pieces as their first move, while the first player can only place 1 piece as their first move.',
  'stimuli_id': '3.0*3.0*3 pieces in a row wins. The second player can place 2 pieces as their first move, while the first player can only place 1 piece as their first move. Horizontal, vertical, and diagonal all count.'},
 {'index': 37,
  'board-x': 5,
  'board-y': 10,
  'N': 5,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*10.0*5 pieces in a row wins.',
  'stimuli_id': '5.0*10.0*5 pieces in a row wins. Horizontal, vertical, and diagonal all count.'}],
[{'index': 11,
  'board-x': 10,
  'board-y': 10,
  'N': 5,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'simple-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '10.0*10.0*5 pieces in a row wins.',
  'stimuli_id': '10.0*10.0*5 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 121,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 0,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'player1-constraintB',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*Each player needs 4 pieces in a row to win. The first player can only win by making a diagonal row, but the second player does not have this restriction.',
  'stimuli_id': '7.0*7.0*Each player needs 4 pieces in a row to win. The first player can only win by making a diagonal row, but the second player does not have this restriction.'},
 {'index': 51,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 0,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'loss',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*4 pieces in a row loses.',
  'stimuli_id': '7.0*7.0*4 pieces in a row loses. Horizontal, vertical, and diagonal all count.'},
 {'index': 63,
  'board-x': 4,
  'board-y': 4,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 0,
  'player2-diag-win': 1,
  'player2-hv-win': 0,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'only-diag',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '4.0*4.0*3 pieces in a row wins. However, a player can only win by making a diagonal row. Horizontal and vertical rows do not count.',
  'stimuli_id': '4.0*4.0*3 pieces in a row wins. However, a player can only win by making a diagonal row. Horizontal and vertical rows do not count.'},
 {'index': 92,
  'board-x': 3,
  'board-y': 3,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 1,
  'player2-2pieces': 0,
  'label': 'player1-2pieces',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '3.0*3.0*3 pieces in a row wins. The first player can place 2 pieces as their first move, while the second player can only place 1 piece as their first move.',
  'stimuli_id': '3.0*3.0*3 pieces in a row wins. The first player can place 2 pieces as their first move, while the second player can only place 1 piece as their first move. Horizontal, vertical, and diagonal all count.'}],
[{'index': 8,
  'board-x': 10,
  'board-y': 10,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'simple-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '10.0*10.0*3 pieces in a row wins.',
  'stimuli_id': '10.0*10.0*3 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 81,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 1,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'diff-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*The first player needs 4 pieces in a row to win, but the second player only needs 3 pieces in a row to win.',
  'stimuli_id': '7.0*7.0*The first player needs 4 pieces in a row to win, but the second player only needs 3 pieces in a row to win. Horizontal, vertical, and diagonal all count.'},
 {'index': 71,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 0,
  'player2-diag-win': 1,
  'player2-hv-win': 0,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'only-diag',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*4 pieces in a row wins. However, a player can only win by making a diagonal row. Horizontal and vertical rows do not count.',
  'stimuli_id': '7.0*7.0*4 pieces in a row wins. However, a player can only win by making a diagonal row. Horizontal and vertical rows do not count.'},
 {'index': 44,
  'board-x': 5,
  'board-y': 5,
  'N': 3,
  'N-for-win': 0,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'loss',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*3 pieces in a row loses.',
  'stimuli_id': '5.0*5.0*3 pieces in a row loses. Horizontal, vertical, and diagonal all count.'},
 {'index': 99,
  'board-x': 5,
  'board-y': 5,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 1,
  'player2-2pieces': 0,
  'label': 'player1-2pieces',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*4 pieces in a row wins. The first player can place 2 pieces as their first move, while the second player can only place 1 piece as their first move.',
  'stimuli_id': '5.0*5.0*4 pieces in a row wins. The first player can place 2 pieces as their first move, while the second player can only place 1 piece as their first move. Horizontal, vertical, and diagonal all count.'}],
[{'index': 24,
  'board-x': 1,
  'board-y': 10,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '1.0*10.0*3 pieces in a row wins.',
  'stimuli_id': '1.0*10.0*3 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 79,
  'board-x': 5,
  'board-y': 5,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 1,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'diff-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*The first player needs 4 pieces in a row to win, but the second player only needs 3 pieces in a row to win.',
  'stimuli_id': '5.0*5.0*The first player needs 4 pieces in a row to win, but the second player only needs 3 pieces in a row to win. Horizontal, vertical, and diagonal all count.'},
 {'index': 114,
  'board-x': 5,
  'board-y': 5,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 0,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'player1-constraintB',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*Each player needs 3 pieces in a row to win. The first player can only win by making a diagonal row, but the second player does not have this restriction.',
  'stimuli_id': '5.0*5.0*Each player needs 3 pieces in a row to win. The first player can only win by making a diagonal row, but the second player does not have this restriction.'},
 {'index': 36,
  'board-x': 5,
  'board-y': 10,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*10.0*4 pieces in a row wins.',
  'stimuli_id': '5.0*10.0*4 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 18,
  'board-x': 5,
  'board-y': 5,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'simple-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*4 pieces in a row wins.',
  'stimuli_id': '5.0*5.0*4 pieces in a row wins. Horizontal, vertical, and diagonal all count.'}],
[{'index': 3,
  'board-x': 5,
  'board-y': 5,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'simple-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*3 pieces in a row wins.',
  'stimuli_id': '5.0*5.0*3 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 101,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 1,
  'player2-2pieces': 0,
  'label': 'player1-2pieces',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*4 pieces in a row wins. The first player can place 2 pieces as their first move, while the second player can only place 1 piece as their first move.',
  'stimuli_id': '7.0*7.0*4 pieces in a row wins. The first player can place 2 pieces as their first move, while the second player can only place 1 piece as their first move. Horizontal, vertical, and diagonal all count.'},
 {'index': 43,
  'board-x': 4,
  'board-y': 4,
  'N': 3,
  'N-for-win': 0,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'loss',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '4.0*4.0*3 pieces in a row loses.',
  'stimuli_id': '4.0*4.0*3 pieces in a row loses. Horizontal, vertical, and diagonal all count.'},
 {'index': 89,
  'board-x': 5,
  'board-y': 5,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 1,
  'label': 'player2-2pieces',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*4 pieces in a row wins. The second player can place 2 pieces as their first move, while the first player can only place 1 piece as their first move.',
  'stimuli_id': '5.0*5.0*4 pieces in a row wins. The second player can place 2 pieces as their first move, while the first player can only place 1 piece as their first move. Horizontal, vertical, and diagonal all count.'},
 {'index': 69,
  'board-x': 5,
  'board-y': 5,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 0,
  'player2-diag-win': 1,
  'player2-hv-win': 0,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'only-diag',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*4 pieces in a row wins. However, a player can only win by making a diagonal row. Horizontal and vertical rows do not count.',
  'stimuli_id': '5.0*5.0*4 pieces in a row wins. However, a player can only win by making a diagonal row. Horizontal and vertical rows do not count.'}],
[{'index': 104,
  'board-x': 5,
  'board-y': 5,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 0,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'player1-constraintA',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*Each player needs 3 pieces in a row to win. The first player cannot win by making a diagonal row (only horizontal and vertical rows count), but the second player does not have this restriction.',
  'stimuli_id': '5.0*5.0*Each player needs 3 pieces in a row to win. The first player cannot win by making a diagonal row (only horizontal and vertical rows count), but the second player does not have this restriction.'},
 {'index': 21,
  'board-x': 7,
  'board-y': 7,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'simple-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '7.0*7.0*4 pieces in a row wins.',
  'stimuli_id': '7.0*7.0*4 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 72,
  'board-x': 3,
  'board-y': 3,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 1,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'diff-win',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '3.0*3.0*The first player needs 3 pieces in a row to win, but the second player only needs 2 pieces in a row to win.',
  'stimuli_id': '3.0*3.0*The first player needs 3 pieces in a row to win, but the second player only needs 2 pieces in a row to win. Horizontal, vertical, and diagonal all count.'},
 {'index': 28,
  'board-x': 3,
  'board-y': 10,
  'N': 3,
  'N-for-win': 1,
  'player1-diag-win': 1,
  'player1-hv-win': 1,
  'player2-diag-win': 1,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'rectangle-board',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '3.0*10.0*3 pieces in a row wins.',
  'stimuli_id': '3.0*10.0*3 pieces in a row wins. Horizontal, vertical, and diagonal all count.'},
 {'index': 59,
  'board-x': 5,
  'board-y': 5,
  'N': 4,
  'N-for-win': 1,
  'player1-diag-win': 0,
  'player1-hv-win': 1,
  'player2-diag-win': 0,
  'player2-hv-win': 1,
  'diff-win': 0,
  'player1-2pieces': 0,
  'player2-2pieces': 0,
  'label': 'no-diag',
  'Unnamed: 13': "nan",
  'human_draw': "nan",
  'model_draw': "nan",
  'random_draw': "nan",
  'Unnamed: 17': "nan",
  'human_win': "nan",
  'model_win': "nan",
  'random_win': "nan",
  'orig_stimuli_id': '5.0*5.0*4 pieces in a row wins. However, a player cannot win by making a diagonal row. Only horizontal and vertical rows count.',
  'stimuli_id': '5.0*5.0*4 pieces in a row wins. However, a player cannot win by making a diagonal row. Only horizontal and vertical rows count.'}]]

function parseStimuliID(stimID) {
  // stimuli IDs are structured as: "numRows*numCols*winConds"
  const parts = stimID.split("*");
  console.log("stimID: ", stimID, "parts: ", parts);
  // note: numRows and numCols are floats and need to be converted to ints
  var numRows = parseInt(parts[0]);
  var numCols = parseInt(parts[1]);
  const winConds = parts[2];

  // further parse the win conditions into special conds for the player
  // and whether K in a row wins or loses

  return {
    numRows: numRows,
    numCols: numCols,
    winConds: winConds,
  };
}

function shuffleArray(array) {
  const newArray = [...array];
  for (let i = newArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
  }
  return newArray;
}

Empirica.onGameStart(({ game }) => {
  const treatment = game.get("treatment");
  console.log("treatment: ", treatment)
  var { numRounds, stimuliBatchID, judgmentTask } = treatment;

  console.log("batch id: ", stimuliBatchID);

  //var origStimBatch = STIMULI_BATCHES[stimuliBatchID]

  // var stimuliBatch = [TIC_TAC_TOE].concat(STIMULI_BATCHES[stimuliBatchID]);
  const origStimBatch = [TIC_TAC_TOE, ...STIMULI_BATCHES[stimuliBatchID]];

  //const origStimBatch = [TIC_TAC_TOE, STIMULI_BATCHES[stimuliBatchID][0]]

  const stimuliBatch = shuffleArray(origStimBatch);

  console.log("stimuli batch: ", stimuliBatch);

  // TODO -- make sure any shuffling is applied the same way to both players
  // https://www.freecodecamp.org/news/how-to-shuffle-an-array-of-items-using-javascript-or-typescript/
  //stimuliBatch.sort(() => Math.random() - 0.5);

  // create an entry for each game round
  for (let j = 0; j < stimuliBatch.length; j++) {
    const stimuliMetaData = stimuliBatch[j];
    const stimuliID = stimuliMetaData["stimuli_id"];

    const { numRows, numCols, winConds } = parseStimuliID(stimuliID);
    console.log("STIMULI ID!! ", stimuliID);

    // num rounds to play any individual game
    for (let i = 0; i < numRounds; i++) {
      const round = game.addRound({
        name: `Round ${i}`,
        // numRows: stimMetadata['numRows'],
        // numCols: stimMetadata['numCols'],
        // winConds: stimMetadata['winConds'],
        numRows: numRows,
        numCols: numCols,
        winConds: winConds,
        stimuliID: stimuliID,
        judgmentTask: judgmentTask,
        stimuliMetaData: stimuliMetaData,
      });

      console.log("added round");

      // NOTE --- set max duration of the game
      // TODO -- if we ask slider questions, need to set a duration so that players keep moving
      // 60 sec?
      // Need fixed instruction time
      var maxGameDuration = 10000;

      round.addStage({ name: "read", duration: 10000 });
      //round.addStage({ name: "judge", duration: 10000 });

      round.addStage({ name: "play", duration: 10000 });
      round.addStage({ name: "judge", duration: 10000 });
    }
  }
});

Empirica.onRoundStart(({ round }) => {
  // Help from GPT
  // Initially, decide the order for the first player randomly
  // var sampledOrder = Math.floor(Math.random() * 2) + 1; // This will give either 1 or 2

  // // NOTE: we will only have two players in a game, so fine to do the following
  // // But this will not work if more than one player is in the game (or single player against model)
  // for (var player of round.currentGame.players) {
  //   // Assign the order to the player
  //   player.round.set("playerOrder", sampledOrder);

  //   // Switch the order for the next player: if the first order was 1, make it 2, and vice versa
  //   sampledOrder = sampledOrder === 1 ? 2 : 1;

  //   player.round.set("gameOutcome", "TBD");

  //   // player.round.set("requestedDraw", "TBD");
  // }

  // Create an array with the possible orders
  let orders = [1, 2];

  // Shuffle the orders array to randomize the order assignment
  orders.sort(() => Math.random() - 0.5);

  // Initialize a dictionary to store player:order pairs
  let playerOrderMap = {};

  // Iterate through the players in the current game and assign the orders
  round.currentGame.players.forEach((player, index) => {
    // Assign the shuffled order to the player
    player.round.set("playerOrder", orders[index]);

    // Map the player to their assigned order in the dictionary
    playerOrderMap[player.id] = orders[index]; // Assuming each player has a unique `id`

    // Set initial game outcome
    player.round.set("gameOutcome", "TBD");
  });


  // init an empty board
  // note: maybe we should move this somewhere else... tbd
  function createGrid(numRows, numCols) {
    const grid = [];
    for (let i = 0; i < numRows; i++) {
      const row = new Array(numCols).fill(0); // Initialize with 0 or any default value
      grid.push(row);
    }
    return grid;
  }
  const gameBoard = createGrid(round.get("numRows"), round.get("numCols"));
  round.set("board", gameBoard);
  round.set("requestedDraw", "None")
  round.set("rejectedDraw", "None")
  round.set("surrenderMade", "None")
  round.set("allBoards", [])
  round.set("allDrawRequests", [])
  round.set("allDrawRejects", [])
  round.set("allDrawAccepts", [])
  round.set("moveTimes", [])

  round.set("playerOrders", playerOrderMap)

});

Empirica.onStageStart(({ stage }) => {
  console.log("start stage");
});

Empirica.onStageEnded(({ stage }) => {
  console.log("end stage");
});

Empirica.onRoundEnded(({ round }) => {});

Empirica.onGameEnded(({ game }) => {});
